@url = http://localhost:3000
@tokenUsr = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDY3YTE3ZDhkMTE1MjU3ZmJkYjg2MCIsImlhdCI6MTYwNzkwOTg2OCwiZXhwIjoxNjA3OTk2MjY4fQ.McvdnuroYq8VJJjloS1IRqvUXKSC3a5XrDeOjVobH3g"
@tokenAdmin = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDY3YTE3ZDhkMTE1MjU3ZmJkYjg2MCIsImlhdCI6MTYwNzkwOTg2OCwiZXhwIjoxNjA3OTk2MjY4fQ.McvdnuroYq8VJJjloS1IRqvUXKSC3a5XrDeOjVobH3g"
@tokenAuthor = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZDY3YTE3ZDhkMTE1MjU3ZmJkYjg2MCIsImlhdCI6MTYwNzkwOTg2OCwiZXhwIjoxNjA3OTk2MjY4fQ.McvdnuroYq8VJJjloS1IRqvUXKSC3a5XrDeOjVobH3g"

// ---------------------- Session ------------------------

### SignUp - User
POST {{url}}/session/signup HTTP/1.1
content-type: application/json

{
  "firstName": "user",
  "lastName": "user",
  "email1": "user00@ingenio.com",
  "password": "User@123",
  "confirmPassword": "User@123"
}

### SignUp - Author
POST {{url}}/session/signup HTTP/1.1
content-type: application/json

{
  "firstName": "author",
  "lastName": "author",
  "email1": "author00@ingenio.com",
  "password": "Author@123",
  "confirmPassword": "User@123"
}

### SignIn - Author
POST {{url}}/session/signin HTTP/1.1
content-type: application/json

{
  "email1": "author00@ingenio.com",
  "password": "Author@123"
}

// ### SignOut

// ---------------------- Category ------------------------

